#!/bin/sh
#export MOZILLA_FIVE_HOME="/usr/lib/xulrunner-1.9.2.17/"
export MOZILLA_FIVE_HOME="/usr/lib/mozilla/"

export LD_LIBRARY_PATH=${MOZILLA_FIVE_HOME}:${LD_LIBRARY_PATH}
export GDK_NATIVE_WINDOWS=1
export ECLIPSE_HOME="/opt/fdt5"

$ECLIPSE_HOME/eclipse $*

